export const questions = [
  // --- Questions from Image 1 (Multiple Choice) ---
  {
    q: "What is the fundamental role of an operating system?",
    options: [
      "To run application software like word processors and games.",
      "To act as an intermediary between the user and the computer hardware.",
      "To provide a connection to the internet.",
      "To manage the computer's power supply.",
    ],
    correct: 1,
    explanation:
      "The OS serves as an interface between the user/applications and the underlying hardware, managing resources efficiently.",
  },
  {
    q: "Which component is considered the 'core' of the operating system and is always running?",
    options: ["Shell", "BIOS", "Kernel", "Compiler"],
    correct: 2,
    explanation:
      "The Kernel is the essential center of the OS, loaded into memory at startup and remaining there until the system shuts down.",
  },
  {
    q: "A signal from a hardware device, like a keyboard or disk drive, that alerts the CPU is called a(n):",
    options: ["System Call", "Trap", "Interrupt", "Exception"],
    correct: 2,
    explanation:
      "An interrupt signals the CPU to suspend its current activities and execute an interrupt handler routine to deal with the event.",
  },
  {
    q: "Which OS structure is characterized by a very small kernel and most services running as user-level processes?",
    options: [
      "Monolithic Kernel",
      "Layered System",
      "Microkernel",
      "Virtual Machine",
    ],
    correct: 2,
    explanation:
      "Microkernels aim to minimize the kernel size by moving as many services as possible (like file system management) into user space.",
  },
  {
    q: "What is the primary purpose of the 'dual-mode' operation in a CPU?",
    options: [
      "To allow the computer to run two operating systems at once.",
      "To enable multiple users to log in simultaneously.",
      "To protect the operating system from errant user programs.",
      "To double the processing speed of the computer.",
    ],
    correct: 2,
    explanation:
      "Dual-mode distinguishes between 'user mode' and 'kernel mode' to prevent user programs from damaging the OS or other programs.",
  },
  {
    q: "The initial program that runs when a computer is powered on is called the:",
    options: ["Kernel", "Bootloader", "Shell", "Init process"],
    correct: 1,
    explanation:
      "The bootstrap loader (or bootloader) locates the operating system kernel and loads it into main memory to start the computer.",
  },
  {
    q: "In a _______ OS structure, the operating system is divided into a number of layers, each built on top of the lower layers.",
    options: ["Simple structure", "More complex", "Layered", "Microkernel"],
    correct: 2,
    explanation:
      "The layered approach modularizes the OS, simplifying debugging and verification.",
  },
  {
    q: "The concept of keeping multiple programs in memory simultaneously to maximize CPU utilization is called:",
    options: [
      "Multitasking",
      "Multiprocessing",
      "Multiprogramming",
      "Multithreading",
    ],
    correct: 2,
    explanation:
      "Multiprogramming ensures the CPU is never idle by keeping several jobs in memory and switching between them when one is waiting for I/O.",
  },
  {
    q: "What is a System Call?",
    options: [
      "A command entered by a user at the command prompt.",
      "A programming interface to request a service from the operating system kernel.",
      "A function within a user application.",
      "An error message generated by a program.",
    ],
    correct: 1,
    explanation:
      "System calls act as the API (Application Programming Interface) between user programs and the operating system.",
  },
  {
    q: "Which of these is a primary function of the OS's Process Management?",
    options: [
      "Allocating and deallocating memory space.",
      "Managing the free space on the hard disk.",
      "Creating, deleting, and scheduling processes.",
      "Translating domain names to IP addresses.",
    ],
    correct: 2,
    explanation:
      "Process management specifically deals with process creation, termination, suspension, and scheduling on the CPU.",
  },

  // --- Questions from Image 2 (Definitions converted to MCQ) ---
  {
    q: "What is a 'Shell' in the context of an Operating System?",
    options: [
      "The core component of the kernel.",
      "A command interpreter that acts as an interface between the user and the OS.",
      "A hardware component protecting the CPU.",
      "The first program to run on startup.",
    ],
    correct: 1,
    explanation:
      "A Shell (like Bash or cmd) interprets user commands and executes them.",
  },
  {
    q: "What is the best definition of a 'Process'?",
    options: [
      "A program in execution.",
      "A static file stored on the hard drive.",
      "A high-speed cache memory.",
      "A type of system interrupt.",
    ],
    correct: 0,
    explanation:
      "A process is an active entity; it is a program that has been loaded into memory and is currently being executed.",
  },
  {
    q: "How does a 'Thread' differ from a process?",
    options: [
      "A thread is a larger unit than a process.",
      "A thread is a basic unit of CPU utilization, often called a lightweight process.",
      "A thread manages the hard disk, while a process manages memory.",
      "Threads run in kernel mode only.",
    ],
    correct: 1,
    explanation:
      "Threads are the smallest sequence of programmed instructions that can be managed independently, existing within a process.",
  },
  {
    q: "What is the function of 'Cache' memory?",
    options: [
      "To store data permanently after shutdown.",
      "To provide high-speed storage for frequently accessed data to reduce CPU wait times.",
      "To manage network connections.",
      "To cool down the processor.",
    ],
    correct: 1,
    explanation:
      "Cache is small, fast memory located close to the CPU that holds copies of frequently used data.",
  },
  {
    q: "What is 'Timesharing' (or Multitasking)?",
    options: [
      "Running only one program at a time until it finishes.",
      "A CPU execution mode where users cannot interact with the system.",
      "The CPU switching jobs so frequently that users can interact with each program while it is running.",
      "Using multiple CPUs to run a single task.",
    ],
    correct: 2,
    explanation:
      "Timesharing is a logical extension of multiprogramming designed to provide interactive use by switching rapidly between tasks.",
  },
  {
    q: "What are 'System Programs'?",
    options: [
      "Programs that provide a convenient environment for program development and execution, distinct from the kernel.",
      "The hardware components of the computer.",
      "Applications like video games and web browsers.",
      "The bootloader code.",
    ],
    correct: 0,
    explanation:
      "System programs (like compilers, editors, and file managers) bundle with the OS but are not part of the kernel code itself.",
  },
  {
    q: "What is a 'Bootstrap Loader'?",
    options: [
      "A program that loads the operating system kernel into memory at startup.",
      "A utility for installing new applications.",
      "A program that cleans up memory leaks.",
      "The physical switch that turns on the computer.",
    ],
    correct: 0,
    explanation:
      "The bootstrap loader is stored in ROM/EEPROM and initializes the system before loading the OS.",
  },
  {
    q: "What is 'Virtual Memory'?",
    options: [
      "A type of virus.",
      "A technique that allows the execution of processes that are not completely in memory.",
      "The physical RAM sticks installed in the motherboard.",
      "Cloud storage utilized by the OS.",
    ],
    correct: 1,
    explanation:
      "Virtual memory abstracts main memory into a large, uniform array of storage, allowing programs larger than physical RAM to run.",
  },
  {
    q: "Which statement best describes an 'Interrupt'?",
    options: [
      "A software error that crashes the system.",
      "A signal to the CPU that an event has occurred which requires immediate attention.",
      "A command to shut down the computer.",
      "A method for increasing internet speed.",
    ],
    correct: 1,
    explanation:
      "Interrupts are the primary way hardware communicates asynchronously with the CPU.",
  },
  {
    q: "What defines an 'Operating System'?",
    options: [
      "A set of hardware components like CPU and RAM.",
      "System software that manages computer hardware and software resources and provides common services for computer programs.",
      "A specific application for word processing.",
      "The internet browser.",
    ],
    correct: 1,
    explanation:
      "This is the broad definition of an OS: the resource manager and coordinator of the computer system.",
  },
];
