export const questions = [
  {
    q: "What is the fundamental role of an operating system?",
    options: [
      "To run application software like word processors and games.",
      "To act as an intermediary between the user and the computer hardware.",
      "To provide a connection to the internet.",
      "To manage the computer's power supply.",
    ],
    correct: 1,
    explanation:
      "As defined in the sources, an operating system is a program that acts as an intermediary between a user of a computer and the computer hardware.",
  },
  {
    q: "Which component is considered the 'core' of the operating system and is always running?",
    options: ["Shell", "BIOS", "Kernel", "Compiler"],
    correct: 2,
    explanation:
      "The kernel is the one program running at all times on the computer; all other components are either system programs or application programs.",
  },
  {
    q: "A signal from a hardware device, like a keyboard or disk drive, that alerts the CPU is called a(n):",
    options: ["System Call", "Trap", "Interrupt", "Exception"],
    correct: 2,
    explanation:
      "Hardware triggers interrupts by sending signals to the CPU, while traps or exceptions are software-generated interrupts.",
  },
  {
    q: "Which OS structure is characterized by a very small kernel and most services running as user-level processes?",
    options: [
      "Monolithic Kernel",
      "Layered System",
      "Microkernel",
      "Virtual Machine",
    ],
    correct: 2,
    explanation:
      "A microkernel structure moves as much as possible from the kernel into user space, resulting in a smaller kernel that handles basic communication between user-level services.",
  },
  {
    q: "What is the primary purpose of the 'dual-mode' operation in a CPU?",
    options: [
      "To allow the computer to run two operating systems at once.",
      "To enable multiple users to log in simultaneously.",
      "To protect the operating system from errant user programs.",
      "To double the processing speed of the computer.",
    ],
    correct: 2,
    explanation:
      "Dual-mode operation (user mode and kernel mode) provides the ability to distinguish when the system is running user code or kernel code, ensuring the OS can protect itself and other components from errors.",
  },
  {
    q: "The initial program that runs when a computer is powered on is called the:",
    options: ["Kernel", "Bootloader", "Shell", "Init process"],
    correct: 1,
    explanation:
      "The bootstrap loader (or bootloader) is a small piece of code stored in ROM or EEPROM that initializes the system, locates the kernel, and starts its execution.",
  },
  {
    q: "In a ________ OS structure, the operating system is divided into a number of layers, each built on top of the lower layers.",
    options: ["Simple structure.", "More complex.", "Layered.", "Microkernel."],
    correct: 2,
    explanation:
      "In a layered OS structure, the system is divided into layers where the bottom layer is the hardware and the highest is the user interface; each layer uses functions of only lower-level layers.",
  },
  {
    q: "The concept of keeping multiple programs in memory simultaneously to maximize CPU utilization is called:",
    options: [
      "Multitasking",
      "Multiprocessing",
      "Multiprogramming",
      "Multithreading",
    ],
    correct: 2,
    explanation:
      "Multiprogramming organizes jobs so that the CPU always has one to execute, thereby increasing efficiency by not letting the CPU sit idle during I/O waits.",
  },
  {
    q: "What is a System Call?",
    options: [
      "A command entered by a user at the command prompt.",
      "A programming interface to request a service from the operating system kernel.",
      "A function within a user application.",
      "An error message generated by a program.",
    ],
    correct: 1,
    explanation:
      "System calls provide the programming interface to the services provided by the operating system, allowing user-level processes to request kernel-level tasks.",
  },
  {
    q: "Which of these is a primary function of the OS's Process Management?",
    options: [
      "Allocating and deallocating memory space.",
      "Managing the free space on the hard disk.",
      "Creating, deleting, and scheduling processes.",
      "Translating domain names to IP addresses.",
    ],
    correct: 2,
    explanation:
      "Process management involves the creation and deletion of user and system processes, as well as their scheduling, synchronization, and communication.",
  },

  // Definitions Section
  {
    q: "Define the term: Shell",
    options: [
      "A command interpreter that reads commands from the user and executes them.",
    ],
    correct: 0,
    explanation:
      "The shell is a user interface that allows direct command entry, primarily by fetching a command from the user and executing it via system calls.",
  },
  {
    q: "Define the term: Interrupt",
    options: [
      "A signal sent to the CPU to indicate an event that requires immediate attention.",
    ],
    correct: 0,
    explanation:
      "An interrupt is a hardware or software signal that stops the CPU's current activity to execute a specific service routine.",
  },
  {
    q: "Define the term: Process",
    options: [
      "A program in execution; an active entity with a program counter and associated resources.",
    ],
    correct: 0,
    explanation:
      "Unlike a passive program on a disk, a process is an active entity in execution that requires resources like CPU time and memory to perform its task.",
  },
  {
    q: "Define the term: Thread",
    options: [
      "A fundamental unit of CPU utilization that allows a process to perform multiple tasks concurrently.",
    ],
    correct: 0,
    explanation:
      "A thread is a light-weight unit of control within a process that can share resources with other threads while maintaining its own program counter.",
  },
  {
    q: "Define the term: Cache",
    options: [
      "A high-speed storage buffer used to improve data transfer between components of varying speeds.",
    ],
    correct: 0,
    explanation:
      "Caches provide a buffer of intermediate speed between two components to ensure that fast devices do not have to wait for slower ones.",
  },
  {
    q: "Define the term: Timesharing or Multitasking",
    options: [
      "An extension of multiprogramming where the CPU switches jobs so frequently that users can interact with each program while it runs.",
    ],
    correct: 0,
    explanation:
      "Timesharing creates an interactive computing environment where the system provides quick response times to multiple users simultaneously.",
  },
  {
    q: "Define the term: System Program",
    options: [
      "Programs that provide a convenient environment for program development and execution, often acting as interfaces to system calls.",
    ],
    correct: 0,
    explanation:
      "System programs can be thought of as bundles of system calls that provide basic functionality for file manipulation, programming support, and system status.",
  },
  {
    q: "Define the term: Operating System",
    options: [
      "A program that acts as an intermediary between a user of a computer and the computer hardware, managing resource allocation and controlling program execution.",
    ],
    correct: 0,
    explanation:
      "According to the sources, an operating system is an intermediary between the user and hardware [2]. Its purposes include providing a convenient environment for program execution, allocating resources fairly and efficiently, and acting as a control program to prevent improper use of the computer [3].",
  },
  {
    q: "Define the term: Bootstrap Loader",
    options: [
      "A small program stored in ROM that initializes the computer system and loads the OS kernel into memory.",
    ],
    correct: 0,
    explanation:
      "This is the initial program that runs when a computer is powered on or rebooted, responsible for starting the operating system.",
  },
  {
    q: "Define the term: Virtual Memory",
    options: [
      "A technique that allows the execution of processes that are not completely in physical memory.",
    ],
    correct: 0,
    explanation:
      "Virtual memory abstracts physical storage, allowing programs to be larger than physical memory and improving system efficiency.",
  },
];
