// Auto-generated by tools/generateExamManifest.js - do not edit by hand
// Run: node tools/generateExamManifest.js

export const examList = [
  {
    "id": "Introduction and Structure",
    "category": "Operatings Systems",
    "title": "Introduction And Structure",
    "path": "../Exams/Operatings Systems/Introduction and Structure.js"
  },
  {
    "id": "Process Concept and Management",
    "category": "Operatings Systems",
    "title": "Process Concept And Management",
    "path": "../Exams/Operatings Systems/Process Concept and Management.js"
  },
  {
    "id": "Quiz on the First Chapter",
    "category": "Operatings Systems",
    "title": "Quiz On The First Chapter",
    "path": "../Exams/Operatings Systems/Quiz on the First Chapter.js"
  },
  {
    "id": "Threads and CPU Scheduling",
    "category": "Operatings Systems",
    "title": "Threads And CPU Scheduling",
    "path": "../Exams/Operatings Systems/Threads and CPU Scheduling.js"
  },
  {
    "id": "Final Exam",
    "category": "Programming 2",
    "title": "Final Exam",
    "path": "../Exams/Programming 2/Final Exam.js"
  },
  {
    "id": "First Chapter quiz",
    "category": "Programming 2",
    "title": "First Chapter Quiz",
    "path": "../Exams/Programming 2/First Chapter quiz.js"
  },
  {
    "id": "Forth and 5th Ch Quiz",
    "category": "Programming 2",
    "title": "Forth And 5th Ch Quiz",
    "path": "../Exams/Programming 2/Forth and 5th Ch Quiz.js"
  },
  {
    "id": "General Quiz",
    "category": "Programming 2",
    "title": "General Quiz",
    "path": "../Exams/Programming 2/General Quiz.js"
  },
  {
    "id": "General Quiz (Hard)",
    "category": "Programming 2",
    "title": "General Quiz (Hard)",
    "path": "../Exams/Programming 2/General Quiz (Hard).js"
  },
  {
    "id": "Quiz 1",
    "category": "Programming 2",
    "title": "Quiz 1",
    "path": "../Exams/Programming 2/Quiz 1.js"
  },
  {
    "id": "Quiz 2",
    "category": "Programming 2",
    "title": "Quiz 2",
    "path": "../Exams/Programming 2/Quiz 2.js"
  },
  {
    "id": "Quiz 3",
    "category": "Programming 2",
    "title": "Quiz 3",
    "path": "../Exams/Programming 2/Quiz 3.js"
  },
  {
    "id": "Quiz 4",
    "category": "Programming 2",
    "title": "Quiz 4",
    "path": "../Exams/Programming 2/Quiz 4.js"
  },
  {
    "id": "Quiz 5",
    "category": "Programming 2",
    "title": "Quiz 5",
    "path": "../Exams/Programming 2/Quiz 5.js"
  },
  {
    "id": "Second Chapter Quiz",
    "category": "Programming 2",
    "title": "Second Chapter Quiz",
    "path": "../Exams/Programming 2/Second Chapter Quiz.js"
  },
  {
    "id": "Sixth and 7th Ch Quiz",
    "category": "Programming 2",
    "title": "Sixth And 7th Ch Quiz",
    "path": "../Exams/Programming 2/Sixth and 7th Ch Quiz.js"
  },
  {
    "id": "Third Chapter Quiz",
    "category": "Programming 2",
    "title": "Third Chapter Quiz",
    "path": "../Exams/Programming 2/Third Chapter Quiz.js"
  }
];
