// Script/examManifest.js
// Auto-generated by ./tools/generateExamManifest.js - do not edit by hand
// Run: node tools/generateExamManifest.js
// Last generated at: 2026/2/7   |   8:50 PM

export const examList = [
  {
    "id": "XW6XWFH2",
    "title": "Introduction To AI",
    "path": "../Exams/Computer Science/2/2/Artificial Intelligence/Introduction to AI.js",
    "category": "Artificial Intelligence"
  },
  {
    "id": "CDU53476",
    "title": "Introduction To Computer Architecture",
    "path": "../Exams/Computer Science/1/2/Computer Architecture/Introduction to Computer Architecture.js",
    "category": "Computer Architecture"
  },
  {
    "id": "4VP7ZUSK",
    "title": "Lecture 2 MCQs",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 2 MCQs.js",
    "category": "Computer Network/أسئلة الدكتورة"
  },
  {
    "id": "DPCHVTXF",
    "title": "Lecture 1 MCQs",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 1 MCQs.js",
    "category": "Computer Network/أسئلة الدكتورة"
  },
  {
    "id": "XOHKYJMX",
    "title": "Lecture 3 MCQs",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 3 MCQs.js",
    "category": "Computer Network/أسئلة الدكتورة"
  },
  {
    "id": "7WKUD2EG",
    "title": "Questions On Computer Networking",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Questions on Computer Networking.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "AMVXGFCM",
    "title": "Revision",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Revision.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "CPON3YWH",
    "title": "Lecture 3",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 3.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "GXYXMGHN",
    "title": "40 MCQs On Lecture 2",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 2.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "HYPVFCZC",
    "title": "Lecture 4",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 4.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "JWGLWAGO",
    "title": "Lecture 6",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 6.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "KN6CTUDC",
    "title": "Lecture 1",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 1.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "MFHPERR2",
    "title": "Lecture 7",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 7.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "PBU25TEU",
    "title": "40 MCQs On Lecture 4",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 4.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "POA3XSRM",
    "title": "Lecture 8",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 8.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "RVZ3HZTG",
    "title": "Lecture 9",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 9.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "SQMPEKO4",
    "title": "CIDAR Notation",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/CIDAR notation.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "TNTPQDDW",
    "title": "Lecture 2",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 2.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "ZJLAWJI2",
    "title": "Lecture 5",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 5.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "3NCTRI5J",
    "title": "Our Mid",
    "path": "../Exams/Computer Science/2/1/Computer Network/Our Mid.js",
    "category": "Computer Network"
  },
  {
    "id": "B2CJ3EQH",
    "title": "Unknown Mid Exam",
    "path": "../Exams/Computer Science/2/1/Computer Network/Unknown Mid Exam.js",
    "category": "Computer Network"
  },
  {
    "id": "CFQQF3HF",
    "title": "IP Address",
    "path": "../Exams/Computer Science/2/1/Computer Network/IP Address.js",
    "category": "Computer Network"
  },
  {
    "id": "MBYDWB7L",
    "title": "فاينل الدكتورة في كلية علوم",
    "path": "../Exams/Computer Science/2/1/Computer Network/فاينل الدكتورة في كلية علوم.js",
    "category": "Computer Network"
  },
  {
    "id": "OIZREUKC",
    "title": "Previous Mid",
    "path": "../Exams/Computer Science/2/1/Computer Network/Previous Mid.js",
    "category": "Computer Network"
  },
  {
    "id": "W4Y2TNSM",
    "title": "Lotus Mid 2",
    "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 2.js",
    "category": "Computer Network"
  },
  {
    "id": "Y6TJV6QU",
    "title": "Lotus Mid 1",
    "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 1.js",
    "category": "Computer Network"
  },
  {
    "id": "U552KHAN",
    "title": "Introduction To Data Structure ",
    "path": "../Exams/Computer Science/2/2/Data Structures and Algorithms/Introduction to Data Structure .js",
    "category": "Data Structures and Algorithms"
  },
  {
    "id": "VTBO2MQ6",
    "title": "Introduction To Database ",
    "path": "../Exams/Computer Science/2/2/Database Management Systems/Introduction to Database .js",
    "category": "Database Management Systems"
  },
  {
    "id": "6VNZX7QX",
    "title": "Revision 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "DUFQJ4E4",
    "title": "Oral 2026 FCI",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Oral 2026 FCI.js",
    "category": "Discrete Structure"
  },
  {
    "id": "HQPR42RS",
    "title": "50 MCQs On Chapter 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/50 MCQs on Chapter 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "JQHYRUHF",
    "title": "Midterm 2025",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2025.js",
    "category": "Discrete Structure"
  },
  {
    "id": "JR7GJMBG",
    "title": "Quiz 5",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 5.js",
    "category": "Discrete Structure"
  },
  {
    "id": "JYZEFHQF",
    "title": "55 MCQs On Chapter 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/55 MCQs on Chapter 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "LANAB2G7",
    "title": "Quiz 4",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 4.js",
    "category": "Discrete Structure"
  },
  {
    "id": "MISB3ITV",
    "title": "Quiz 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "OWZS27YE",
    "title": "Midterm 2023",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2023.js",
    "category": "Discrete Structure"
  },
  {
    "id": "QHIUOVTX",
    "title": "Midterm 2026",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2026.js",
    "category": "Discrete Structure"
  },
  {
    "id": "QXHZHLTK",
    "title": "Quiz 3",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 3.js",
    "category": "Discrete Structure"
  },
  {
    "id": "SM3FSK3Q",
    "title": "Practical Exam   Model A",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Practical Exam - Model A.js",
    "category": "Discrete Structure"
  },
  {
    "id": "U2V7HEVB",
    "title": "Revision 2",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 2.js",
    "category": "Discrete Structure"
  },
  {
    "id": "V3XFKYUI",
    "title": "Quiz 2",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 2.js",
    "category": "Discrete Structure"
  },
  {
    "id": "V672XWWO",
    "title": "MCQs On Chapter 2",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/MCQs on Chapter 2.js",
    "category": "Discrete Structure"
  },
  {
    "id": "OI3VNH6I",
    "title": "Introduction To Electronics",
    "path": "../Exams/Computer Science/1/2/Electronics/Introduction to Electronics.js",
    "category": "Electronics"
  },
  {
    "id": "2RWIAS54",
    "title": "Ch 8 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch 8 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "66GBAEPF",
    "title": "Midterm Exam",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Midterm Exam.js",
    "category": "Foundation of IS"
  },
  {
    "id": "7DGDTOMT",
    "title": "Ch1, 2, And 3 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1, 2, and 3 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "AL65QZB4",
    "title": "Ch1 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "BAAV6TBY",
    "title": "Ch6 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch6 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "IZWZO2SA",
    "title": "General AI Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/General AI quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "LRQUDRMG",
    "title": "General Exam",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/General Exam.js",
    "category": "Foundation of IS"
  },
  {
    "id": "X6FZ2NU6",
    "title": "Introduction To Math 2",
    "path": "../Exams/Computer Science/1/2/Math 2/Introduction to Math 2.js",
    "category": "Math 2"
  },
  {
    "id": "N4AHNEV2",
    "title": "Final Exam",
    "path": "../Exams/Computer Science/2/1/Object-Oriented Programming/Final Exam.js",
    "category": "Object-Oriented Programming"
  },
  {
    "id": "7DHJAUAN",
    "title": "2. Operating Systems Structures",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/2. Operating Systems Structures.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "DZ2DCBLE",
    "title": "3. Processes",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/3. Processes.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "E64WRP5W",
    "title": "1. Introduction",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/1. Introduction.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "RRBLYR77",
    "title": "4. Threads",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/4. Threads.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "WAHZHBT2",
    "title": "6. CPU Scheduling",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/6. CPU Scheduling.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "4HMF5FE7",
    "title": "1. Introduction",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/1. Introduction.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "ALTZUWZ5",
    "title": "6. CPU Scheduling",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/6. CPU Scheduling.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "ESGNPX3K",
    "title": "4. Threads",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/4. Threads.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "JXTFKHBS",
    "title": "3. Processes",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/3. Processes.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "PN6M2XZC",
    "title": "2. Operating Systems Structures",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/2. Operating Systems Structures.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "26VDGKRR",
    "title": "Ch1 Zaqazeeq",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch1 Zaqazeeq.js",
    "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
  },
  {
    "id": "FCOUTIO4",
    "title": "Ch3 Zaqazeeq",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch3 Zaqazeeq.js",
    "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
  },
  {
    "id": "HGWATJX7",
    "title": "Ch2 Zaqazeeq",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch2 Zaqazeeq.js",
    "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
  },
  {
    "id": "4KBC2NDZ",
    "title": "Threads And CPU Scheduling",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Threads and CPU Scheduling.js",
    "category": "Operatings Systems"
  },
  {
    "id": "63TNHSSU",
    "title": "Ch 6 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 6 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "73KVCOVB",
    "title": "General Exam 3",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 3.js",
    "category": "Operatings Systems"
  },
  {
    "id": "7JEK3XG4",
    "title": "Ch1 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "APZQA777",
    "title": "أسئلة مقالي",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي.js",
    "category": "Operatings Systems"
  },
  {
    "id": "AUNR6JGZ",
    "title": "General Exam 2",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 2.js",
    "category": "Operatings Systems"
  },
  {
    "id": "AY5TSS5G",
    "title": "أسئلة مقالي 2",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي 2.js",
    "category": "Operatings Systems"
  },
  {
    "id": "BF6K7HTR",
    "title": "Quiz On The First Chapter",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Quiz on the First Chapter.js",
    "category": "Operatings Systems"
  },
  {
    "id": "CMX2WPFI",
    "title": "Final السنة اللي فاتت",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Final السنة اللي فاتت.js",
    "category": "Operatings Systems"
  },
  {
    "id": "DZDOJ7RV",
    "title": "Ch3 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch3 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "F7DQPHSV",
    "title": "Ch 1, 2, 3, And 4 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 1, 2, 3, and 4 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "KIPO3QUN",
    "title": "Ch 4 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 4 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "QYTKT4BY",
    "title": "General Exam",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam.js",
    "category": "Operatings Systems"
  },
  {
    "id": "TOL5XZCO",
    "title": "Midterm Exam",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Midterm Exam.js",
    "category": "Operatings Systems"
  },
  {
    "id": "WAMNIN7N",
    "title": "Ch2 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch2 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "ZNXZYJ44",
    "title": "Ch1 And 2 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 and 2 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "ZSDTOIEZ",
    "title": "Introduction And Structure",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Introduction and Structure.js",
    "category": "Operatings Systems"
  },
  {
    "id": "ZUREKPJT",
    "title": "Process Concept And Management",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Process Concept and Management.js",
    "category": "Operatings Systems"
  },
  {
    "id": "6TYK4CLQ",
    "title": "Introduction To Probability ",
    "path": "../Exams/Computer Science/2/2/Probability and Statistics/Introduction to Probability .js",
    "category": "Probability and Statistics"
  },
  {
    "id": "Y2TK2ZQ5",
    "title": "Introduction To C Sharp",
    "path": "../Exams/Computer Science/1/2/Programming 1/Introduction to C Sharp.js",
    "category": "Programming 1"
  },
  {
    "id": "3UCKOBJY",
    "title": "Quiz 1",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 1.js",
    "category": "Programming 2"
  },
  {
    "id": "4TH433ET",
    "title": "First Chapter Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/First Chapter quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "5G6574PK",
    "title": "Forth And 5th Ch Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Forth and 5th Ch Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "AUK5TG6K",
    "title": "Second Chapter Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Second Chapter Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "FZQBSZ3G",
    "title": "General Quiz (Hard)",
    "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz (Hard).js",
    "category": "Programming 2"
  },
  {
    "id": "GVDSSCI7",
    "title": "Quiz 3",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 3.js",
    "category": "Programming 2"
  },
  {
    "id": "PAH3JJAW",
    "title": "Sixth And 7th Ch Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Sixth and 7th Ch Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "PSEF27UP",
    "title": "Quiz 5",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 5.js",
    "category": "Programming 2"
  },
  {
    "id": "QYFKHBLC",
    "title": "Third Chapter Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Third Chapter Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "RRKXT32Z",
    "title": "Final Exam",
    "path": "../Exams/Computer Science/2/1/Programming 2/Final Exam.js",
    "category": "Programming 2"
  },
  {
    "id": "S4KBXSKN",
    "title": "General Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "VFICUDLS",
    "title": "Quiz 4",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 4.js",
    "category": "Programming 2"
  },
  {
    "id": "YAHTW2OR",
    "title": "Quiz 2",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 2.js",
    "category": "Programming 2"
  },
  {
    "id": "7YKRP5LV",
    "title": "Introduction To Scientific Thinking",
    "path": "../Exams/Computer Science/1/2/Scientific thinking/Introduction to Scientific Thinking.js",
    "category": "Scientific thinking"
  },
  {
    "id": "4WO7J7L7",
    "title": "Introduction To Server Lab ",
    "path": "../Exams/Computer Science/2/2/Server Lab/Introduction to Server Lab .js",
    "category": "Server Lab"
  },
  {
    "id": "WGCMYTV4",
    "title": "Image Support Demo",
    "path": "../Exams/Computer Science/2/2/Server Lab/Image Support Demo.js",
    "category": "Server Lab"
  },
  {
    "id": "IY5A3RU5",
    "title": "Introduction To System ",
    "path": "../Exams/Computer Science/2/2/System Analysis and Design/Introduction to System .js",
    "category": "System Analysis and Design"
  },
  {
    "id": "7N3UUQRN",
    "title": "Introduction To Technical Writing",
    "path": "../Exams/Computer Science/1/2/Technical Writing/Introduction to Technical Writing.js",
    "category": "Technical Writing"
  }
];

export const categoryTree = {
  "Computer Architecture": {
    "id": "DHUGLDJX",
    "name": "Computer Architecture",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Computer Architecture"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "CDU53476",
        "title": "Introduction To Computer Architecture",
        "path": "../Exams/Computer Science/1/2/Computer Architecture/Introduction to Computer Architecture.js",
        "category": "Computer Architecture"
      }
    ]
  },
  "Electronics": {
    "id": "7XXUN2TX",
    "name": "Electronics",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Electronics"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "OI3VNH6I",
        "title": "Introduction To Electronics",
        "path": "../Exams/Computer Science/1/2/Electronics/Introduction to Electronics.js",
        "category": "Electronics"
      }
    ]
  },
  "Math 2": {
    "id": "BKI5DMN7",
    "name": "Math 2",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Math 2"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "X6FZ2NU6",
        "title": "Introduction To Math 2",
        "path": "../Exams/Computer Science/1/2/Math 2/Introduction to Math 2.js",
        "category": "Math 2"
      }
    ]
  },
  "Programming 1": {
    "id": "FYYB3QBX",
    "name": "Programming 1",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Programming 1"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "Y2TK2ZQ5",
        "title": "Introduction To C Sharp",
        "path": "../Exams/Computer Science/1/2/Programming 1/Introduction to C Sharp.js",
        "category": "Programming 1"
      }
    ]
  },
  "Scientific thinking": {
    "id": "TRKXYLTS",
    "name": "Scientific thinking",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Scientific thinking"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "7YKRP5LV",
        "title": "Introduction To Scientific Thinking",
        "path": "../Exams/Computer Science/1/2/Scientific thinking/Introduction to Scientific Thinking.js",
        "category": "Scientific thinking"
      }
    ]
  },
  "Technical Writing": {
    "id": "5W63WOO7",
    "name": "Technical Writing",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Technical Writing"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "7N3UUQRN",
        "title": "Introduction To Technical Writing",
        "path": "../Exams/Computer Science/1/2/Technical Writing/Introduction to Technical Writing.js",
        "category": "Technical Writing"
      }
    ]
  },
  "Computer Network": {
    "id": "JNPSKUT7",
    "name": "Computer Network",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Computer Network"
    ],
    "parent": null,
    "subcategories": [
      "Computer Network/أسئلة الدكتورة",
      "Computer Network/أسئلة بالذكاء الإصطناعي"
    ],
    "exams": [
      {
        "id": "CFQQF3HF",
        "title": "IP Address",
        "path": "../Exams/Computer Science/2/1/Computer Network/IP Address.js",
        "category": "Computer Network"
      },
      {
        "id": "Y6TJV6QU",
        "title": "Lotus Mid 1",
        "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 1.js",
        "category": "Computer Network"
      },
      {
        "id": "W4Y2TNSM",
        "title": "Lotus Mid 2",
        "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 2.js",
        "category": "Computer Network"
      },
      {
        "id": "3NCTRI5J",
        "title": "Our Mid",
        "path": "../Exams/Computer Science/2/1/Computer Network/Our Mid.js",
        "category": "Computer Network"
      },
      {
        "id": "OIZREUKC",
        "title": "Previous Mid",
        "path": "../Exams/Computer Science/2/1/Computer Network/Previous Mid.js",
        "category": "Computer Network"
      },
      {
        "id": "B2CJ3EQH",
        "title": "Unknown Mid Exam",
        "path": "../Exams/Computer Science/2/1/Computer Network/Unknown Mid Exam.js",
        "category": "Computer Network"
      },
      {
        "id": "MBYDWB7L",
        "title": "فاينل الدكتورة في كلية علوم",
        "path": "../Exams/Computer Science/2/1/Computer Network/فاينل الدكتورة في كلية علوم.js",
        "category": "Computer Network"
      }
    ]
  },
  "Computer Network/أسئلة الدكتورة": {
    "name": "أسئلة الدكتورة",
    "path": [
      "Computer Network",
      "أسئلة الدكتورة"
    ],
    "parent": "Computer Network",
    "subcategories": [],
    "exams": [
      {
        "id": "DPCHVTXF",
        "title": "Lecture 1 MCQs",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 1 MCQs.js",
        "category": "Computer Network/أسئلة الدكتورة"
      },
      {
        "id": "4VP7ZUSK",
        "title": "Lecture 2 MCQs",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 2 MCQs.js",
        "category": "Computer Network/أسئلة الدكتورة"
      },
      {
        "id": "XOHKYJMX",
        "title": "Lecture 3 MCQs",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 3 MCQs.js",
        "category": "Computer Network/أسئلة الدكتورة"
      }
    ]
  },
  "Computer Network/أسئلة بالذكاء الإصطناعي": {
    "name": "أسئلة بالذكاء الإصطناعي",
    "path": [
      "Computer Network",
      "أسئلة بالذكاء الإصطناعي"
    ],
    "parent": "Computer Network",
    "subcategories": [],
    "exams": [
      {
        "id": "GXYXMGHN",
        "title": "40 MCQs On Lecture 2",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 2.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "PBU25TEU",
        "title": "40 MCQs On Lecture 4",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 4.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "SQMPEKO4",
        "title": "CIDAR Notation",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/CIDAR notation.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "KN6CTUDC",
        "title": "Lecture 1",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 1.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "TNTPQDDW",
        "title": "Lecture 2",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 2.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "CPON3YWH",
        "title": "Lecture 3",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 3.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "HYPVFCZC",
        "title": "Lecture 4",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 4.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "ZJLAWJI2",
        "title": "Lecture 5",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 5.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "JWGLWAGO",
        "title": "Lecture 6",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 6.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "MFHPERR2",
        "title": "Lecture 7",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 7.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "POA3XSRM",
        "title": "Lecture 8",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 8.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "RVZ3HZTG",
        "title": "Lecture 9",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 9.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "7WKUD2EG",
        "title": "Questions On Computer Networking",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Questions on Computer Networking.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "AMVXGFCM",
        "title": "Revision",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Revision.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      }
    ]
  },
  "Discrete Structure": {
    "id": "J6JB6VLU",
    "name": "Discrete Structure",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Discrete Structure"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "HQPR42RS",
        "title": "50 MCQs On Chapter 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/50 MCQs on Chapter 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "JYZEFHQF",
        "title": "55 MCQs On Chapter 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/55 MCQs on Chapter 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "V672XWWO",
        "title": "MCQs On Chapter 2",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/MCQs on Chapter 2.js",
        "category": "Discrete Structure"
      },
      {
        "id": "OWZS27YE",
        "title": "Midterm 2023",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2023.js",
        "category": "Discrete Structure"
      },
      {
        "id": "JQHYRUHF",
        "title": "Midterm 2025",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2025.js",
        "category": "Discrete Structure"
      },
      {
        "id": "QHIUOVTX",
        "title": "Midterm 2026",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2026.js",
        "category": "Discrete Structure"
      },
      {
        "id": "DUFQJ4E4",
        "title": "Oral 2026 FCI",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Oral 2026 FCI.js",
        "category": "Discrete Structure"
      },
      {
        "id": "SM3FSK3Q",
        "title": "Practical Exam   Model A",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Practical Exam - Model A.js",
        "category": "Discrete Structure"
      },
      {
        "id": "MISB3ITV",
        "title": "Quiz 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "V3XFKYUI",
        "title": "Quiz 2",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 2.js",
        "category": "Discrete Structure"
      },
      {
        "id": "QXHZHLTK",
        "title": "Quiz 3",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 3.js",
        "category": "Discrete Structure"
      },
      {
        "id": "LANAB2G7",
        "title": "Quiz 4",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 4.js",
        "category": "Discrete Structure"
      },
      {
        "id": "JR7GJMBG",
        "title": "Quiz 5",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 5.js",
        "category": "Discrete Structure"
      },
      {
        "id": "6VNZX7QX",
        "title": "Revision 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "U2V7HEVB",
        "title": "Revision 2",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 2.js",
        "category": "Discrete Structure"
      }
    ]
  },
  "Foundation of IS": {
    "id": "XC7OAP25",
    "name": "Foundation of IS",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Foundation of IS"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "2RWIAS54",
        "title": "Ch 8 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch 8 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "AL65QZB4",
        "title": "Ch1 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "7DGDTOMT",
        "title": "Ch1, 2, And 3 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1, 2, and 3 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "BAAV6TBY",
        "title": "Ch6 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch6 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "IZWZO2SA",
        "title": "General AI Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/General AI quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "LRQUDRMG",
        "title": "General Exam",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/General Exam.js",
        "category": "Foundation of IS"
      },
      {
        "id": "66GBAEPF",
        "title": "Midterm Exam",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Midterm Exam.js",
        "category": "Foundation of IS"
      }
    ]
  },
  "Object-Oriented Programming": {
    "id": "YYMJPTLY",
    "name": "Object-Oriented Programming",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Object-Oriented Programming"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "N4AHNEV2",
        "title": "Final Exam",
        "path": "../Exams/Computer Science/2/1/Object-Oriented Programming/Final Exam.js",
        "category": "Object-Oriented Programming"
      }
    ]
  },
  "Operatings Systems": {
    "id": "SJYTGCUQ",
    "name": "Operatings Systems",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Operatings Systems"
    ],
    "parent": null,
    "subcategories": [
      "Operatings Systems/أسئلة الدكتور اللي مش محلولة",
      "Operatings Systems/أسئلة الدكتور المحلولة",
      "Operatings Systems/إمتحانات جامعة الزقازيق"
    ],
    "exams": [
      {
        "id": "F7DQPHSV",
        "title": "Ch 1, 2, 3, And 4 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 1, 2, 3, and 4 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "KIPO3QUN",
        "title": "Ch 4 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 4 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "63TNHSSU",
        "title": "Ch 6 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 6 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "ZNXZYJ44",
        "title": "Ch1 And 2 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 and 2 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "7JEK3XG4",
        "title": "Ch1 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "WAMNIN7N",
        "title": "Ch2 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch2 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "DZDOJ7RV",
        "title": "Ch3 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch3 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "CMX2WPFI",
        "title": "Final السنة اللي فاتت",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Final السنة اللي فاتت.js",
        "category": "Operatings Systems"
      },
      {
        "id": "AUNR6JGZ",
        "title": "General Exam 2",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 2.js",
        "category": "Operatings Systems"
      },
      {
        "id": "73KVCOVB",
        "title": "General Exam 3",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 3.js",
        "category": "Operatings Systems"
      },
      {
        "id": "QYTKT4BY",
        "title": "General Exam",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam.js",
        "category": "Operatings Systems"
      },
      {
        "id": "ZSDTOIEZ",
        "title": "Introduction And Structure",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Introduction and Structure.js",
        "category": "Operatings Systems"
      },
      {
        "id": "TOL5XZCO",
        "title": "Midterm Exam",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Midterm Exam.js",
        "category": "Operatings Systems"
      },
      {
        "id": "ZUREKPJT",
        "title": "Process Concept And Management",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Process Concept and Management.js",
        "category": "Operatings Systems"
      },
      {
        "id": "BF6K7HTR",
        "title": "Quiz On The First Chapter",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Quiz on the First Chapter.js",
        "category": "Operatings Systems"
      },
      {
        "id": "4KBC2NDZ",
        "title": "Threads And CPU Scheduling",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Threads and CPU Scheduling.js",
        "category": "Operatings Systems"
      },
      {
        "id": "AY5TSS5G",
        "title": "أسئلة مقالي 2",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي 2.js",
        "category": "Operatings Systems"
      },
      {
        "id": "APZQA777",
        "title": "أسئلة مقالي",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي.js",
        "category": "Operatings Systems"
      }
    ]
  },
  "Operatings Systems/أسئلة الدكتور اللي مش محلولة": {
    "name": "أسئلة الدكتور اللي مش محلولة",
    "path": [
      "Operatings Systems",
      "أسئلة الدكتور اللي مش محلولة"
    ],
    "parent": "Operatings Systems",
    "subcategories": [],
    "exams": [
      {
        "id": "E64WRP5W",
        "title": "1. Introduction",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/1. Introduction.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "7DHJAUAN",
        "title": "2. Operating Systems Structures",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/2. Operating Systems Structures.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "DZ2DCBLE",
        "title": "3. Processes",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/3. Processes.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "RRBLYR77",
        "title": "4. Threads",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/4. Threads.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "WAHZHBT2",
        "title": "6. CPU Scheduling",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/6. CPU Scheduling.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      }
    ]
  },
  "Operatings Systems/أسئلة الدكتور المحلولة": {
    "name": "أسئلة الدكتور المحلولة",
    "path": [
      "Operatings Systems",
      "أسئلة الدكتور المحلولة"
    ],
    "parent": "Operatings Systems",
    "subcategories": [],
    "exams": [
      {
        "id": "4HMF5FE7",
        "title": "1. Introduction",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/1. Introduction.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "PN6M2XZC",
        "title": "2. Operating Systems Structures",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/2. Operating Systems Structures.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "JXTFKHBS",
        "title": "3. Processes",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/3. Processes.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "ESGNPX3K",
        "title": "4. Threads",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/4. Threads.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "ALTZUWZ5",
        "title": "6. CPU Scheduling",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/6. CPU Scheduling.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      }
    ]
  },
  "Operatings Systems/إمتحانات جامعة الزقازيق": {
    "name": "إمتحانات جامعة الزقازيق",
    "path": [
      "Operatings Systems",
      "إمتحانات جامعة الزقازيق"
    ],
    "parent": "Operatings Systems",
    "subcategories": [],
    "exams": [
      {
        "id": "26VDGKRR",
        "title": "Ch1 Zaqazeeq",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch1 Zaqazeeq.js",
        "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
      },
      {
        "id": "HGWATJX7",
        "title": "Ch2 Zaqazeeq",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch2 Zaqazeeq.js",
        "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
      },
      {
        "id": "FCOUTIO4",
        "title": "Ch3 Zaqazeeq",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch3 Zaqazeeq.js",
        "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
      }
    ]
  },
  "Programming 2": {
    "id": "3ZEXV6OX",
    "name": "Programming 2",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Programming 2"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "RRKXT32Z",
        "title": "Final Exam",
        "path": "../Exams/Computer Science/2/1/Programming 2/Final Exam.js",
        "category": "Programming 2"
      },
      {
        "id": "4TH433ET",
        "title": "First Chapter Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/First Chapter quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "5G6574PK",
        "title": "Forth And 5th Ch Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Forth and 5th Ch Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "FZQBSZ3G",
        "title": "General Quiz (Hard)",
        "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz (Hard).js",
        "category": "Programming 2"
      },
      {
        "id": "S4KBXSKN",
        "title": "General Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "3UCKOBJY",
        "title": "Quiz 1",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 1.js",
        "category": "Programming 2"
      },
      {
        "id": "YAHTW2OR",
        "title": "Quiz 2",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 2.js",
        "category": "Programming 2"
      },
      {
        "id": "GVDSSCI7",
        "title": "Quiz 3",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 3.js",
        "category": "Programming 2"
      },
      {
        "id": "VFICUDLS",
        "title": "Quiz 4",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 4.js",
        "category": "Programming 2"
      },
      {
        "id": "PSEF27UP",
        "title": "Quiz 5",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 5.js",
        "category": "Programming 2"
      },
      {
        "id": "AUK5TG6K",
        "title": "Second Chapter Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Second Chapter Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "PAH3JJAW",
        "title": "Sixth And 7th Ch Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Sixth and 7th Ch Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "QYFKHBLC",
        "title": "Third Chapter Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Third Chapter Quiz.js",
        "category": "Programming 2"
      }
    ]
  },
  "Artificial Intelligence": {
    "id": "BL4EOEV5",
    "name": "Artificial Intelligence",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Artificial Intelligence"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "XW6XWFH2",
        "title": "Introduction To AI",
        "path": "../Exams/Computer Science/2/2/Artificial Intelligence/Introduction to AI.js",
        "category": "Artificial Intelligence"
      }
    ]
  },
  "Data Structures and Algorithms": {
    "id": "ED6AG4MN",
    "name": "Data Structures and Algorithms",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Data Structures and Algorithms"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "U552KHAN",
        "title": "Introduction To Data Structure ",
        "path": "../Exams/Computer Science/2/2/Data Structures and Algorithms/Introduction to Data Structure .js",
        "category": "Data Structures and Algorithms"
      }
    ]
  },
  "Database Management Systems": {
    "id": "UAALMGDR",
    "name": "Database Management Systems",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Database Management Systems"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "VTBO2MQ6",
        "title": "Introduction To Database ",
        "path": "../Exams/Computer Science/2/2/Database Management Systems/Introduction to Database .js",
        "category": "Database Management Systems"
      }
    ]
  },
  "Probability and Statistics": {
    "id": "SWLLQTER",
    "name": "Probability and Statistics",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Probability and Statistics"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "6TYK4CLQ",
        "title": "Introduction To Probability ",
        "path": "../Exams/Computer Science/2/2/Probability and Statistics/Introduction to Probability .js",
        "category": "Probability and Statistics"
      }
    ]
  },
  "Server Lab": {
    "id": "KMWJK2L7",
    "name": "Server Lab",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Server Lab"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "WGCMYTV4",
        "title": "Image Support Demo",
        "path": "../Exams/Computer Science/2/2/Server Lab/Image Support Demo.js",
        "category": "Server Lab"
      },
      {
        "id": "4WO7J7L7",
        "title": "Introduction To Server Lab ",
        "path": "../Exams/Computer Science/2/2/Server Lab/Introduction to Server Lab .js",
        "category": "Server Lab"
      }
    ]
  },
  "System Analysis and Design": {
    "id": "KFSNUFKL",
    "name": "System Analysis and Design",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "System Analysis and Design"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "IY5A3RU5",
        "title": "Introduction To System ",
        "path": "../Exams/Computer Science/2/2/System Analysis and Design/Introduction to System .js",
        "category": "System Analysis and Design"
      }
    ]
  }
};
