// Script/examManifest.js
// Auto-generated by ./tools/generateExamManifest.js - do not edit by hand
// Run: node tools/generateExamManifest.js
// Last generated at: 2026/2/9   |   4:50 PM

export const examList = [
  {
    "id": "NZTWDBCY",
    "title": "Introduction To AI",
    "path": "../Exams/Computer Science/2/2/Artificial Intelligence/Introduction to AI.js",
    "category": "Artificial Intelligence"
  },
  {
    "id": "OYGGPKTO",
    "title": "Introduction To Computer Architecture",
    "path": "../Exams/Computer Science/1/2/Computer Architecture/Introduction to Computer Architecture.js",
    "category": "Computer Architecture"
  },
  {
    "id": "DWS2A24Q",
    "title": "Lecture 2 MCQs",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 2 MCQs.js",
    "category": "Computer Network/أسئلة الدكتورة"
  },
  {
    "id": "SKNZXGTA",
    "title": "Lecture 3 MCQs",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 3 MCQs.js",
    "category": "Computer Network/أسئلة الدكتورة"
  },
  {
    "id": "USDH5VOJ",
    "title": "Lecture 1 MCQs",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 1 MCQs.js",
    "category": "Computer Network/أسئلة الدكتورة"
  },
  {
    "id": "3YPVGOWU",
    "title": "Lecture 6",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 6.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "B4VFNUPZ",
    "title": "Lecture 5",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 5.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "DEW24JZM",
    "title": "40 MCQs On Lecture 2",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 2.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "EC26XDNT",
    "title": "Lecture 9",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 9.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "FZANSYOO",
    "title": "Lecture 1",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 1.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "GXWUM6KA",
    "title": "Lecture 3",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 3.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "GZ6QQ4EG",
    "title": "40 MCQs On Lecture 4",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 4.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "H73LJLOF",
    "title": "Questions On Computer Networking",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Questions on Computer Networking.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "HFGXQV3P",
    "title": "Lecture 7",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 7.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "MEHZIFLL",
    "title": "Lecture 8",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 8.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "MFGQBH7T",
    "title": "Lecture 2",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 2.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "O3G6WAT7",
    "title": "Revision",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Revision.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "OGUHA3WF",
    "title": "Lecture 4",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 4.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "R4MLTYLW",
    "title": "CIDAR Notation",
    "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/CIDAR notation.js",
    "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
  },
  {
    "id": "5INCZMJJ",
    "title": "Previous Mid",
    "path": "../Exams/Computer Science/2/1/Computer Network/Previous Mid.js",
    "category": "Computer Network"
  },
  {
    "id": "GVFKKCJI",
    "title": "Our Mid",
    "path": "../Exams/Computer Science/2/1/Computer Network/Our Mid.js",
    "category": "Computer Network"
  },
  {
    "id": "HRHSTT4O",
    "title": "IP Address",
    "path": "../Exams/Computer Science/2/1/Computer Network/IP Address.js",
    "category": "Computer Network"
  },
  {
    "id": "QEQ7ATNM",
    "title": "Unknown Mid Exam",
    "path": "../Exams/Computer Science/2/1/Computer Network/Unknown Mid Exam.js",
    "category": "Computer Network"
  },
  {
    "id": "QGYRZPOX",
    "title": "Lotus Mid 2",
    "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 2.js",
    "category": "Computer Network"
  },
  {
    "id": "TM4RZLPC",
    "title": "Lotus Mid 1",
    "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 1.js",
    "category": "Computer Network"
  },
  {
    "id": "WOP7VGLW",
    "title": "فاينل الدكتورة في كلية علوم",
    "path": "../Exams/Computer Science/2/1/Computer Network/فاينل الدكتورة في كلية علوم.js",
    "category": "Computer Network"
  },
  {
    "id": "IUHJ53RE",
    "title": "Introduction To Data Structure ",
    "path": "../Exams/Computer Science/2/2/Data Structures and Algorithms/Introduction to Data Structure .js",
    "category": "Data Structures and Algorithms"
  },
  {
    "id": "5GSHKMOD",
    "title": "Introduction To Database ",
    "path": "../Exams/Computer Science/2/2/Database Management Systems/Introduction to Database .js",
    "category": "Database Management Systems"
  },
  {
    "id": "3TT2TQLX",
    "title": "50 MCQs On Chapter 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/50 MCQs on Chapter 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "4CRBEHC2",
    "title": "Revision 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "ASPEZRPU",
    "title": "MCQs On Chapter 2",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/MCQs on Chapter 2.js",
    "category": "Discrete Structure"
  },
  {
    "id": "B72CZVL6",
    "title": "Oral 2026 FCI",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Oral 2026 FCI.js",
    "category": "Discrete Structure"
  },
  {
    "id": "BO2OQJJ2",
    "title": "Quiz 3",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 3.js",
    "category": "Discrete Structure"
  },
  {
    "id": "DUWMJXRD",
    "title": "Midterm 2025",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2025.js",
    "category": "Discrete Structure"
  },
  {
    "id": "I4VCRY4T",
    "title": "Quiz 2",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 2.js",
    "category": "Discrete Structure"
  },
  {
    "id": "JBHQTDZH",
    "title": "Midterm 2026",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2026.js",
    "category": "Discrete Structure"
  },
  {
    "id": "KXG2Q2WO",
    "title": "Quiz 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "O7SR3UWF",
    "title": "Practical Exam   Model A",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Practical Exam - Model A.js",
    "category": "Discrete Structure"
  },
  {
    "id": "OZMX5E6N",
    "title": "Midterm 2023",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2023.js",
    "category": "Discrete Structure"
  },
  {
    "id": "RDSNPZ2B",
    "title": "Quiz 5",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 5.js",
    "category": "Discrete Structure"
  },
  {
    "id": "TBL5OMBM",
    "title": "Revision 2",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 2.js",
    "category": "Discrete Structure"
  },
  {
    "id": "V325BF6T",
    "title": "Quiz 4",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 4.js",
    "category": "Discrete Structure"
  },
  {
    "id": "XK7S5SQV",
    "title": "55 MCQs On Chapter 1",
    "path": "../Exams/Computer Science/2/1/Discrete Structure/55 MCQs on Chapter 1.js",
    "category": "Discrete Structure"
  },
  {
    "id": "7BGUXR6F",
    "title": "Introduction To Electronics",
    "path": "../Exams/Computer Science/1/2/Electronics/Introduction to Electronics.js",
    "category": "Electronics"
  },
  {
    "id": "4YJWUH3N",
    "title": "Ch6 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch6 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "7FMKCIWF",
    "title": "General AI Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/General AI quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "H6W2CNI4",
    "title": "General Exam",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/General Exam.js",
    "category": "Foundation of IS"
  },
  {
    "id": "J6VW5HAU",
    "title": "Ch 8 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch 8 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "MI4SSC6C",
    "title": "Midterm Exam",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Midterm Exam.js",
    "category": "Foundation of IS"
  },
  {
    "id": "PQVDPN2A",
    "title": "Ch1 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "XXKU7BRS",
    "title": "Ch1, 2, And 3 Quiz",
    "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1, 2, and 3 Quiz.js",
    "category": "Foundation of IS"
  },
  {
    "id": "6RCMDDHJ",
    "title": "Introduction To Math 2",
    "path": "../Exams/Computer Science/1/2/Math 2/Introduction to Math 2.js",
    "category": "Math 2"
  },
  {
    "id": "7KH2OSLF",
    "title": "Final Exam",
    "path": "../Exams/Computer Science/2/1/Object-Oriented Programming/Final Exam.js",
    "category": "Object-Oriented Programming"
  },
  {
    "id": "23LKRHRP",
    "title": "1. Introduction",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/1. Introduction.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "JUO27YZH",
    "title": "2. Operating Systems Structures",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/2. Operating Systems Structures.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "K5LWWENX",
    "title": "6. CPU Scheduling",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/6. CPU Scheduling.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "LKYHDQBN",
    "title": "3. Processes",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/3. Processes.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "UTOGPIXF",
    "title": "4. Threads",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/4. Threads.js",
    "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
  },
  {
    "id": "AEOGC2PZ",
    "title": "2. Operating Systems Structures",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/2. Operating Systems Structures.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "BPKSGXKW",
    "title": "3. Processes",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/3. Processes.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "LQ3JVA7G",
    "title": "1. Introduction",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/1. Introduction.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "RKXQD7DB",
    "title": "6. CPU Scheduling",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/6. CPU Scheduling.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "VHOHPFTY",
    "title": "4. Threads",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/4. Threads.js",
    "category": "Operatings Systems/أسئلة الدكتور المحلولة"
  },
  {
    "id": "MFS2GX6C",
    "title": "Ch1 Zaqazeeq",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch1 Zaqazeeq.js",
    "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
  },
  {
    "id": "MM75SUSQ",
    "title": "Ch2 Zaqazeeq",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch2 Zaqazeeq.js",
    "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
  },
  {
    "id": "NQI6ULOB",
    "title": "Ch3 Zaqazeeq",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch3 Zaqazeeq.js",
    "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
  },
  {
    "id": "3QKPPTFH",
    "title": "General Exam 2",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 2.js",
    "category": "Operatings Systems"
  },
  {
    "id": "3YEOTHCV",
    "title": "Ch 4 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 4 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "7JBXRI52",
    "title": "General Exam 3",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 3.js",
    "category": "Operatings Systems"
  },
  {
    "id": "7SVA4MIM",
    "title": "أسئلة مقالي",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي.js",
    "category": "Operatings Systems"
  },
  {
    "id": "C53366UH",
    "title": "Final السنة اللي فاتت",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Final السنة اللي فاتت.js",
    "category": "Operatings Systems"
  },
  {
    "id": "GRGDU7WV",
    "title": "Ch 1, 2, 3, And 4 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 1, 2, 3, and 4 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "HZTE7AP5",
    "title": "Ch 6 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 6 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "MDEZ2QWU",
    "title": "أسئلة مقالي 2",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي 2.js",
    "category": "Operatings Systems"
  },
  {
    "id": "MT6NHJ4H",
    "title": "Ch1 And 2 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 and 2 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "P42A3RUJ",
    "title": "Process Concept And Management",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Process Concept and Management.js",
    "category": "Operatings Systems"
  },
  {
    "id": "P52C363G",
    "title": "Introduction And Structure",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Introduction and Structure.js",
    "category": "Operatings Systems"
  },
  {
    "id": "QZLQZPAG",
    "title": "Ch2 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch2 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "SDXR73N3",
    "title": "General Exam",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam.js",
    "category": "Operatings Systems"
  },
  {
    "id": "SQTSBW5D",
    "title": "Ch3 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch3 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "SWXAEFYS",
    "title": "Threads And CPU Scheduling",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Threads and CPU Scheduling.js",
    "category": "Operatings Systems"
  },
  {
    "id": "UMZRS25T",
    "title": "Midterm Exam",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Midterm Exam.js",
    "category": "Operatings Systems"
  },
  {
    "id": "V6CNGU6V",
    "title": "Quiz On The First Chapter",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Quiz on the First Chapter.js",
    "category": "Operatings Systems"
  },
  {
    "id": "YEBDCA7J",
    "title": "Ch1 Quiz",
    "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 Quiz.js",
    "category": "Operatings Systems"
  },
  {
    "id": "WBV4UA6Q",
    "title": "Introduction To Probability ",
    "path": "../Exams/Computer Science/2/2/Probability and Statistics/Introduction to Probability .js",
    "category": "Probability and Statistics"
  },
  {
    "id": "2GF5RUB7",
    "title": "Introduction To C Sharp",
    "path": "../Exams/Computer Science/1/2/Programming 1/Introduction to C Sharp.js",
    "category": "Programming 1"
  },
  {
    "id": "42R53SO2",
    "title": "General Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "5CXCHRKX",
    "title": "Quiz 3",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 3.js",
    "category": "Programming 2"
  },
  {
    "id": "B45QXHHU",
    "title": "Final Exam",
    "path": "../Exams/Computer Science/2/1/Programming 2/Final Exam.js",
    "category": "Programming 2"
  },
  {
    "id": "E3JZOHW5",
    "title": "First Chapter Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/First Chapter quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "ISKECPOV",
    "title": "Forth And 5th Ch Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Forth and 5th Ch Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "KM3TKS7J",
    "title": "Third Chapter Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Third Chapter Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "L6QP5PXG",
    "title": "Quiz 2",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 2.js",
    "category": "Programming 2"
  },
  {
    "id": "MR43LQR3",
    "title": "Second Chapter Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Second Chapter Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "PPZS6OGV",
    "title": "Quiz 5",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 5.js",
    "category": "Programming 2"
  },
  {
    "id": "RBLZK3DL",
    "title": "Sixth And 7th Ch Quiz",
    "path": "../Exams/Computer Science/2/1/Programming 2/Sixth and 7th Ch Quiz.js",
    "category": "Programming 2"
  },
  {
    "id": "RDL3UJ3V",
    "title": "Quiz 4",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 4.js",
    "category": "Programming 2"
  },
  {
    "id": "V2TV7TJK",
    "title": "Quiz 1",
    "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 1.js",
    "category": "Programming 2"
  },
  {
    "id": "VI6YDBXJ",
    "title": "General Quiz (Hard)",
    "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz (Hard).js",
    "category": "Programming 2"
  },
  {
    "id": "5GINDAAE",
    "title": "Introduction To Scientific Thinking",
    "path": "../Exams/Computer Science/1/2/Scientific thinking/Introduction to Scientific Thinking.js",
    "category": "Scientific thinking"
  },
  {
    "id": "53OZCMMQ",
    "title": "Website Demo",
    "path": "../Exams/Computer Science/2/2/Server Lab/Website Demo.js",
    "category": "Server Lab"
  },
  {
    "id": "WPHV7INH",
    "title": "Introduction To Server Lab ",
    "path": "../Exams/Computer Science/2/2/Server Lab/Introduction to Server Lab .js",
    "category": "Server Lab"
  },
  {
    "id": "J2PK7GVN",
    "title": "Introduction To System ",
    "path": "../Exams/Computer Science/2/2/System Analysis and Design/Introduction to System .js",
    "category": "System Analysis and Design"
  },
  {
    "id": "BJUEOOA7",
    "title": "Introduction To Technical Writing",
    "path": "../Exams/Computer Science/1/2/Technical Writing/Introduction to Technical Writing.js",
    "category": "Technical Writing"
  }
];

export const categoryTree = {
  "Computer Architecture": {
    "id": "3AME5JAA",
    "name": "Computer Architecture",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Computer Architecture"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "OYGGPKTO",
        "title": "Introduction To Computer Architecture",
        "path": "../Exams/Computer Science/1/2/Computer Architecture/Introduction to Computer Architecture.js",
        "category": "Computer Architecture"
      }
    ]
  },
  "Electronics": {
    "id": "4PW2DRF4",
    "name": "Electronics",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Electronics"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "7BGUXR6F",
        "title": "Introduction To Electronics",
        "path": "../Exams/Computer Science/1/2/Electronics/Introduction to Electronics.js",
        "category": "Electronics"
      }
    ]
  },
  "Math 2": {
    "id": "Z2YYJ4HS",
    "name": "Math 2",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Math 2"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "6RCMDDHJ",
        "title": "Introduction To Math 2",
        "path": "../Exams/Computer Science/1/2/Math 2/Introduction to Math 2.js",
        "category": "Math 2"
      }
    ]
  },
  "Programming 1": {
    "id": "Z7SBWVAB",
    "name": "Programming 1",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Programming 1"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "2GF5RUB7",
        "title": "Introduction To C Sharp",
        "path": "../Exams/Computer Science/1/2/Programming 1/Introduction to C Sharp.js",
        "category": "Programming 1"
      }
    ]
  },
  "Scientific thinking": {
    "id": "6I5CH6YP",
    "name": "Scientific thinking",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Scientific thinking"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "5GINDAAE",
        "title": "Introduction To Scientific Thinking",
        "path": "../Exams/Computer Science/1/2/Scientific thinking/Introduction to Scientific Thinking.js",
        "category": "Scientific thinking"
      }
    ]
  },
  "Technical Writing": {
    "id": "NKFWZ6VC",
    "name": "Technical Writing",
    "faculty": "Computer Science",
    "year": "1",
    "term": "2",
    "path": [
      "Technical Writing"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "BJUEOOA7",
        "title": "Introduction To Technical Writing",
        "path": "../Exams/Computer Science/1/2/Technical Writing/Introduction to Technical Writing.js",
        "category": "Technical Writing"
      }
    ]
  },
  "Computer Network": {
    "id": "IICCWRPK",
    "name": "Computer Network",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Computer Network"
    ],
    "parent": null,
    "subcategories": [
      "Computer Network/أسئلة الدكتورة",
      "Computer Network/أسئلة بالذكاء الإصطناعي"
    ],
    "exams": [
      {
        "id": "HRHSTT4O",
        "title": "IP Address",
        "path": "../Exams/Computer Science/2/1/Computer Network/IP Address.js",
        "category": "Computer Network"
      },
      {
        "id": "TM4RZLPC",
        "title": "Lotus Mid 1",
        "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 1.js",
        "category": "Computer Network"
      },
      {
        "id": "QGYRZPOX",
        "title": "Lotus Mid 2",
        "path": "../Exams/Computer Science/2/1/Computer Network/Lotus Mid 2.js",
        "category": "Computer Network"
      },
      {
        "id": "GVFKKCJI",
        "title": "Our Mid",
        "path": "../Exams/Computer Science/2/1/Computer Network/Our Mid.js",
        "category": "Computer Network"
      },
      {
        "id": "5INCZMJJ",
        "title": "Previous Mid",
        "path": "../Exams/Computer Science/2/1/Computer Network/Previous Mid.js",
        "category": "Computer Network"
      },
      {
        "id": "QEQ7ATNM",
        "title": "Unknown Mid Exam",
        "path": "../Exams/Computer Science/2/1/Computer Network/Unknown Mid Exam.js",
        "category": "Computer Network"
      },
      {
        "id": "WOP7VGLW",
        "title": "فاينل الدكتورة في كلية علوم",
        "path": "../Exams/Computer Science/2/1/Computer Network/فاينل الدكتورة في كلية علوم.js",
        "category": "Computer Network"
      }
    ]
  },
  "Computer Network/أسئلة الدكتورة": {
    "name": "أسئلة الدكتورة",
    "path": [
      "Computer Network",
      "أسئلة الدكتورة"
    ],
    "parent": "Computer Network",
    "subcategories": [],
    "exams": [
      {
        "id": "USDH5VOJ",
        "title": "Lecture 1 MCQs",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 1 MCQs.js",
        "category": "Computer Network/أسئلة الدكتورة"
      },
      {
        "id": "DWS2A24Q",
        "title": "Lecture 2 MCQs",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 2 MCQs.js",
        "category": "Computer Network/أسئلة الدكتورة"
      },
      {
        "id": "SKNZXGTA",
        "title": "Lecture 3 MCQs",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة الدكتورة/Lecture 3 MCQs.js",
        "category": "Computer Network/أسئلة الدكتورة"
      }
    ]
  },
  "Computer Network/أسئلة بالذكاء الإصطناعي": {
    "name": "أسئلة بالذكاء الإصطناعي",
    "path": [
      "Computer Network",
      "أسئلة بالذكاء الإصطناعي"
    ],
    "parent": "Computer Network",
    "subcategories": [],
    "exams": [
      {
        "id": "DEW24JZM",
        "title": "40 MCQs On Lecture 2",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 2.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "GZ6QQ4EG",
        "title": "40 MCQs On Lecture 4",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/40 MCQs on Lecture 4.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "R4MLTYLW",
        "title": "CIDAR Notation",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/CIDAR notation.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "FZANSYOO",
        "title": "Lecture 1",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 1.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "MFGQBH7T",
        "title": "Lecture 2",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 2.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "GXWUM6KA",
        "title": "Lecture 3",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 3.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "OGUHA3WF",
        "title": "Lecture 4",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 4.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "B4VFNUPZ",
        "title": "Lecture 5",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 5.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "3YPVGOWU",
        "title": "Lecture 6",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 6.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "HFGXQV3P",
        "title": "Lecture 7",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 7.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "MEHZIFLL",
        "title": "Lecture 8",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 8.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "EC26XDNT",
        "title": "Lecture 9",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Lecture 9.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "H73LJLOF",
        "title": "Questions On Computer Networking",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Questions on Computer Networking.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      },
      {
        "id": "O3G6WAT7",
        "title": "Revision",
        "path": "../Exams/Computer Science/2/1/Computer Network/أسئلة بالذكاء الإصطناعي/Revision.js",
        "category": "Computer Network/أسئلة بالذكاء الإصطناعي"
      }
    ]
  },
  "Discrete Structure": {
    "id": "ASGPL5NA",
    "name": "Discrete Structure",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Discrete Structure"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "3TT2TQLX",
        "title": "50 MCQs On Chapter 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/50 MCQs on Chapter 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "XK7S5SQV",
        "title": "55 MCQs On Chapter 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/55 MCQs on Chapter 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "ASPEZRPU",
        "title": "MCQs On Chapter 2",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/MCQs on Chapter 2.js",
        "category": "Discrete Structure"
      },
      {
        "id": "OZMX5E6N",
        "title": "Midterm 2023",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2023.js",
        "category": "Discrete Structure"
      },
      {
        "id": "DUWMJXRD",
        "title": "Midterm 2025",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2025.js",
        "category": "Discrete Structure"
      },
      {
        "id": "JBHQTDZH",
        "title": "Midterm 2026",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Midterm 2026.js",
        "category": "Discrete Structure"
      },
      {
        "id": "B72CZVL6",
        "title": "Oral 2026 FCI",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Oral 2026 FCI.js",
        "category": "Discrete Structure"
      },
      {
        "id": "O7SR3UWF",
        "title": "Practical Exam   Model A",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Practical Exam - Model A.js",
        "category": "Discrete Structure"
      },
      {
        "id": "KXG2Q2WO",
        "title": "Quiz 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "I4VCRY4T",
        "title": "Quiz 2",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 2.js",
        "category": "Discrete Structure"
      },
      {
        "id": "BO2OQJJ2",
        "title": "Quiz 3",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 3.js",
        "category": "Discrete Structure"
      },
      {
        "id": "V325BF6T",
        "title": "Quiz 4",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 4.js",
        "category": "Discrete Structure"
      },
      {
        "id": "RDSNPZ2B",
        "title": "Quiz 5",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Quiz 5.js",
        "category": "Discrete Structure"
      },
      {
        "id": "4CRBEHC2",
        "title": "Revision 1",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 1.js",
        "category": "Discrete Structure"
      },
      {
        "id": "TBL5OMBM",
        "title": "Revision 2",
        "path": "../Exams/Computer Science/2/1/Discrete Structure/Revision 2.js",
        "category": "Discrete Structure"
      }
    ]
  },
  "Foundation of IS": {
    "id": "CAZE2FM5",
    "name": "Foundation of IS",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Foundation of IS"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "J6VW5HAU",
        "title": "Ch 8 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch 8 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "PQVDPN2A",
        "title": "Ch1 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "XXKU7BRS",
        "title": "Ch1, 2, And 3 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch1, 2, and 3 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "4YJWUH3N",
        "title": "Ch6 Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Ch6 Quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "7FMKCIWF",
        "title": "General AI Quiz",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/General AI quiz.js",
        "category": "Foundation of IS"
      },
      {
        "id": "H6W2CNI4",
        "title": "General Exam",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/General Exam.js",
        "category": "Foundation of IS"
      },
      {
        "id": "MI4SSC6C",
        "title": "Midterm Exam",
        "path": "../Exams/Computer Science/2/1/Foundation of IS/Midterm Exam.js",
        "category": "Foundation of IS"
      }
    ]
  },
  "Object-Oriented Programming": {
    "id": "HAG3Y76S",
    "name": "Object-Oriented Programming",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Object-Oriented Programming"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "7KH2OSLF",
        "title": "Final Exam",
        "path": "../Exams/Computer Science/2/1/Object-Oriented Programming/Final Exam.js",
        "category": "Object-Oriented Programming"
      }
    ]
  },
  "Operatings Systems": {
    "id": "FFI33CCX",
    "name": "Operatings Systems",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Operatings Systems"
    ],
    "parent": null,
    "subcategories": [
      "Operatings Systems/أسئلة الدكتور اللي مش محلولة",
      "Operatings Systems/أسئلة الدكتور المحلولة",
      "Operatings Systems/إمتحانات جامعة الزقازيق"
    ],
    "exams": [
      {
        "id": "GRGDU7WV",
        "title": "Ch 1, 2, 3, And 4 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 1, 2, 3, and 4 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "3YEOTHCV",
        "title": "Ch 4 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 4 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "HZTE7AP5",
        "title": "Ch 6 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch 6 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "MT6NHJ4H",
        "title": "Ch1 And 2 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 and 2 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "YEBDCA7J",
        "title": "Ch1 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch1 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "QZLQZPAG",
        "title": "Ch2 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch2 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "SQTSBW5D",
        "title": "Ch3 Quiz",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Ch3 Quiz.js",
        "category": "Operatings Systems"
      },
      {
        "id": "C53366UH",
        "title": "Final السنة اللي فاتت",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Final السنة اللي فاتت.js",
        "category": "Operatings Systems"
      },
      {
        "id": "3QKPPTFH",
        "title": "General Exam 2",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 2.js",
        "category": "Operatings Systems"
      },
      {
        "id": "7JBXRI52",
        "title": "General Exam 3",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam 3.js",
        "category": "Operatings Systems"
      },
      {
        "id": "SDXR73N3",
        "title": "General Exam",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/General Exam.js",
        "category": "Operatings Systems"
      },
      {
        "id": "P52C363G",
        "title": "Introduction And Structure",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Introduction and Structure.js",
        "category": "Operatings Systems"
      },
      {
        "id": "UMZRS25T",
        "title": "Midterm Exam",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Midterm Exam.js",
        "category": "Operatings Systems"
      },
      {
        "id": "P42A3RUJ",
        "title": "Process Concept And Management",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Process Concept and Management.js",
        "category": "Operatings Systems"
      },
      {
        "id": "V6CNGU6V",
        "title": "Quiz On The First Chapter",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Quiz on the First Chapter.js",
        "category": "Operatings Systems"
      },
      {
        "id": "SWXAEFYS",
        "title": "Threads And CPU Scheduling",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/Threads and CPU Scheduling.js",
        "category": "Operatings Systems"
      },
      {
        "id": "MDEZ2QWU",
        "title": "أسئلة مقالي 2",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي 2.js",
        "category": "Operatings Systems"
      },
      {
        "id": "7SVA4MIM",
        "title": "أسئلة مقالي",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة مقالي.js",
        "category": "Operatings Systems"
      }
    ]
  },
  "Operatings Systems/أسئلة الدكتور اللي مش محلولة": {
    "name": "أسئلة الدكتور اللي مش محلولة",
    "path": [
      "Operatings Systems",
      "أسئلة الدكتور اللي مش محلولة"
    ],
    "parent": "Operatings Systems",
    "subcategories": [],
    "exams": [
      {
        "id": "23LKRHRP",
        "title": "1. Introduction",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/1. Introduction.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "JUO27YZH",
        "title": "2. Operating Systems Structures",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/2. Operating Systems Structures.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "LKYHDQBN",
        "title": "3. Processes",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/3. Processes.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "UTOGPIXF",
        "title": "4. Threads",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/4. Threads.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      },
      {
        "id": "K5LWWENX",
        "title": "6. CPU Scheduling",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور اللي مش محلولة/6. CPU Scheduling.js",
        "category": "Operatings Systems/أسئلة الدكتور اللي مش محلولة"
      }
    ]
  },
  "Operatings Systems/أسئلة الدكتور المحلولة": {
    "name": "أسئلة الدكتور المحلولة",
    "path": [
      "Operatings Systems",
      "أسئلة الدكتور المحلولة"
    ],
    "parent": "Operatings Systems",
    "subcategories": [],
    "exams": [
      {
        "id": "LQ3JVA7G",
        "title": "1. Introduction",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/1. Introduction.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "AEOGC2PZ",
        "title": "2. Operating Systems Structures",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/2. Operating Systems Structures.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "BPKSGXKW",
        "title": "3. Processes",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/3. Processes.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "VHOHPFTY",
        "title": "4. Threads",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/4. Threads.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      },
      {
        "id": "RKXQD7DB",
        "title": "6. CPU Scheduling",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/أسئلة الدكتور المحلولة/6. CPU Scheduling.js",
        "category": "Operatings Systems/أسئلة الدكتور المحلولة"
      }
    ]
  },
  "Operatings Systems/إمتحانات جامعة الزقازيق": {
    "name": "إمتحانات جامعة الزقازيق",
    "path": [
      "Operatings Systems",
      "إمتحانات جامعة الزقازيق"
    ],
    "parent": "Operatings Systems",
    "subcategories": [],
    "exams": [
      {
        "id": "MFS2GX6C",
        "title": "Ch1 Zaqazeeq",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch1 Zaqazeeq.js",
        "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
      },
      {
        "id": "MM75SUSQ",
        "title": "Ch2 Zaqazeeq",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch2 Zaqazeeq.js",
        "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
      },
      {
        "id": "NQI6ULOB",
        "title": "Ch3 Zaqazeeq",
        "path": "../Exams/Computer Science/2/1/Operatings Systems/إمتحانات جامعة الزقازيق/Ch3 Zaqazeeq.js",
        "category": "Operatings Systems/إمتحانات جامعة الزقازيق"
      }
    ]
  },
  "Programming 2": {
    "id": "KQ5OO3Q7",
    "name": "Programming 2",
    "faculty": "Computer Science",
    "year": "2",
    "term": "1",
    "path": [
      "Programming 2"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "B45QXHHU",
        "title": "Final Exam",
        "path": "../Exams/Computer Science/2/1/Programming 2/Final Exam.js",
        "category": "Programming 2"
      },
      {
        "id": "E3JZOHW5",
        "title": "First Chapter Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/First Chapter quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "ISKECPOV",
        "title": "Forth And 5th Ch Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Forth and 5th Ch Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "VI6YDBXJ",
        "title": "General Quiz (Hard)",
        "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz (Hard).js",
        "category": "Programming 2"
      },
      {
        "id": "42R53SO2",
        "title": "General Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/General Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "V2TV7TJK",
        "title": "Quiz 1",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 1.js",
        "category": "Programming 2"
      },
      {
        "id": "L6QP5PXG",
        "title": "Quiz 2",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 2.js",
        "category": "Programming 2"
      },
      {
        "id": "5CXCHRKX",
        "title": "Quiz 3",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 3.js",
        "category": "Programming 2"
      },
      {
        "id": "RDL3UJ3V",
        "title": "Quiz 4",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 4.js",
        "category": "Programming 2"
      },
      {
        "id": "PPZS6OGV",
        "title": "Quiz 5",
        "path": "../Exams/Computer Science/2/1/Programming 2/Quiz 5.js",
        "category": "Programming 2"
      },
      {
        "id": "MR43LQR3",
        "title": "Second Chapter Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Second Chapter Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "RBLZK3DL",
        "title": "Sixth And 7th Ch Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Sixth and 7th Ch Quiz.js",
        "category": "Programming 2"
      },
      {
        "id": "KM3TKS7J",
        "title": "Third Chapter Quiz",
        "path": "../Exams/Computer Science/2/1/Programming 2/Third Chapter Quiz.js",
        "category": "Programming 2"
      }
    ]
  },
  "Artificial Intelligence": {
    "id": "AOPHQ5FO",
    "name": "Artificial Intelligence",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Artificial Intelligence"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "NZTWDBCY",
        "title": "Introduction To AI",
        "path": "../Exams/Computer Science/2/2/Artificial Intelligence/Introduction to AI.js",
        "category": "Artificial Intelligence"
      }
    ]
  },
  "Data Structures and Algorithms": {
    "id": "JCRH6MZK",
    "name": "Data Structures and Algorithms",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Data Structures and Algorithms"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "IUHJ53RE",
        "title": "Introduction To Data Structure ",
        "path": "../Exams/Computer Science/2/2/Data Structures and Algorithms/Introduction to Data Structure .js",
        "category": "Data Structures and Algorithms"
      }
    ]
  },
  "Database Management Systems": {
    "id": "JN4JJVIG",
    "name": "Database Management Systems",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Database Management Systems"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "5GSHKMOD",
        "title": "Introduction To Database ",
        "path": "../Exams/Computer Science/2/2/Database Management Systems/Introduction to Database .js",
        "category": "Database Management Systems"
      }
    ]
  },
  "Probability and Statistics": {
    "id": "N3YVMU7F",
    "name": "Probability and Statistics",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Probability and Statistics"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "WBV4UA6Q",
        "title": "Introduction To Probability ",
        "path": "../Exams/Computer Science/2/2/Probability and Statistics/Introduction to Probability .js",
        "category": "Probability and Statistics"
      }
    ]
  },
  "Server Lab": {
    "id": "E6RPFLJZ",
    "name": "Server Lab",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "Server Lab"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "WPHV7INH",
        "title": "Introduction To Server Lab ",
        "path": "../Exams/Computer Science/2/2/Server Lab/Introduction to Server Lab .js",
        "category": "Server Lab"
      },
      {
        "id": "53OZCMMQ",
        "title": "Website Demo",
        "path": "../Exams/Computer Science/2/2/Server Lab/Website Demo.js",
        "category": "Server Lab"
      }
    ]
  },
  "System Analysis and Design": {
    "id": "4ZH7R2FF",
    "name": "System Analysis and Design",
    "faculty": "Computer Science",
    "year": "2",
    "term": "2",
    "path": [
      "System Analysis and Design"
    ],
    "parent": null,
    "subcategories": [],
    "exams": [
      {
        "id": "J2PK7GVN",
        "title": "Introduction To System ",
        "path": "../Exams/Computer Science/2/2/System Analysis and Design/Introduction to System .js",
        "category": "System Analysis and Design"
      }
    ]
  }
};
